export const FETCH_WEATHER = 'FETCH_WEATHER';

export const FETCH_TIDES = 'FETCH_TIDES';

export const FETCH_EXPRESS_WEATHER = 'FETCH_EXPRESS_WEATHER';

export const FETCH_EXPRESS_TIDES = 'FETCH_EXPRESS_TIDES';

export const FETCH_MONGODB_WEATHER = 'FETCH_MONGODB_WEATHER';

export const FETCH_MONGODB_TIDES = 'FETCH_MONGODB_TIDES';

export const FETCH_PLACEHOLDER = 'FETCH_PLACEHOLDER';

export const FETCH_NEW_TIDES = 'FETCH_NEW_TIDES';
